<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datatypes [
<!ELEMENT datatypes (type+)>
<!ELEMENT type (qualified_name,prefix,suffix,import)>
<!ELEMENT qualified_name (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>
<!ELEMENT suffix (#PCDATA)>
<!ELEMENT import (#PCDATA)>
]>

<datatypes>
	<type>
		<qualified_name>java.math.BigDecimal</qualified_name>
		<prefix>l</prefix>
		<suffix>_bigdecimal</suffix>
		<import>T</import>
	</type>
	<type>
		<qualified_name>java.math.BigInteger</qualified_name>
		<prefix>bi</prefix>
		<suffix>_biginteger</suffix>
		<import>T</import>
	</type>
	<type>
		<qualified_name>java.sql.Timestamp</qualified_name>
		<prefix>ts</prefix>
		<suffix>_timestamp</suffix>
		<import>T</import>
	</type>
	<type>
		<qualified_name>java.sql.Date</qualified_name>
		<prefix>dt</prefix>
		<suffix>_date</suffix>
		<import>T</import>
	</type>
	<type>
		<qualified_name>Integer</qualified_name>
		<prefix>i</prefix>
		<suffix>_integer</suffix>
		<import>F</import>
	</type>
	<type>
		<qualified_name>String</qualified_name>
		<prefix>str</prefix>
		<suffix>_string</suffix>
		<import>F</import>
	</type>
	<type>
		<qualified_name>Float</qualified_name>
		<prefix>fl</prefix>
		<suffix>_float</suffix>
		<import>F</import>
	</type>
	<type>
		<qualified_name>Double</qualified_name>
		<prefix>dl</prefix>
		<suffix>_double</suffix>
		<import>F</import>
	</type>
	<type>
		<qualified_name>Long</qualified_name>
		<prefix>lg</prefix>
		<suffix>_long</suffix>
		<import>F</import>
	</type>
	<type>
		<qualified_name>Object</qualified_name>
		<prefix>o</prefix>
		<suffix>_object</suffix>
		<import>F</import>
	</type>
	<type>
		<qualified_name>java.util.List</qualified_name>
		<prefix>lst</prefix>
		<suffix>_list</suffix>
		<import>T</import>
	</type>
	<type>
		<qualified_name>java.util.Map</qualified_name>
		<prefix>map</prefix>
		<suffix>_map</suffix>
		<import>T</import>
	</type>
	<type>
		<qualified_name>java.util.Set</qualified_name>
		<prefix>set</prefix>
		<suffix>_set</suffix>
		<import>T</import>
	</type>
</datatypes>
